### ISSUE TITLE
Images: Right-clicking an image gives a URL that can be included in the website.

### ISSUE THREAD

**Issue by tristanengst** [ihstsa/ihstsa.github.io#2]
![Uploading ihstsatogether 2.JPG . . .]()
![Uploading swin 2.jpg . . .]()
![Uploading ffwin.jpg . . .]()

**Comment by tristanengst** [comment]
![swin 2](https://cloud.githubusercontent.com/assets/3527106/5697022/9871e93e-99b2-11e4-98f1-e87f23fe048a.jpg)

**Comment by tristanengst** [comment]
![image](https://cloud.githubusercontent.com/assets/3527106/6100308/52a9179e-afdb-11e4-98b2-6366e337b5fb.png)

**Comment by tristanengst** [comment]
![back](https://cloud.githubusercontent.com/assets/3527106/6100311/65582704-afdb-11e4-8e88-82f751bdbb6a.png)

**Comment by tristanengst** [comment]
![business card](https://cloud.githubusercontent.com/assets/3527106/6100315/86913640-afdb-11e4-847f-00660029aed5.png)

**Comment by tristanengst** [comment]
![wins](https://cloud.githubusercontent.com/assets/3527106/6100613/e70f1474-afe0-11e4-8aaf-a893e1d7b573.png)

**Comment by tristanengst** [comment]
![win](https://cloud.githubusercontent.com/assets/3527106/6100750/c136c398-afe3-11e4-849f-13939f515061.png)

**Comment by pbfy0** [comment]
This is still not the correct way to include images. Do it the right way. I've removed your write access to the repository.
